version: 2
updates:
  # Set update schedule for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      interval: "monthly"
  # Set update schedule for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every month
      # Align with pre-commit configuration .pre-commit-config.yaml
      interval: "monthly"
